package com.bosgii.internshipmanagement.enums;

public enum InternshipStatus {
	WAITING_FOR_INFORMATION,
	WAITING_FOR_COMPANY_APPROVAL,
	FAIL_COMPANY_APPROVAL,
	NOT_SUBMITTED,
	FAIL_NO_SUBMISSION,
	UNDER_EVALUATION,
	FAIL_UNSATISFACTORY_REPORT,
	SUCCESSFUL
}
